# Docker Compose configuration for the morphic-stack development environment

name: Bastion-chat
services:
  morphic:
    build:
      context: .
      dockerfile: Dockerfile
    image: morphic:local
    command: bun start -H 0.0.0.0
    env_file: .env.local # Load environment variables
    environment:
      USE_LOCAL_REDIS: 'true'
      LOCAL_REDIS_URL: 'redis://redis:6379'
    ports:
      - '4320:3000' # Maps port 3000 on the host to port 3000 in the container.
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data:
